//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGiris.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCari()
        {
            this.tblStokCikisUsts = new HashSet<tblStokCikisUst>();
            this.tblStokGirisUsts = new HashSet<tblStokGirisUst>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CariTip { get; set; }
        public string CariKod { get; set; }
        public string CariAd { get; set; }
        public string Adres { get; set; }
        public Nullable<int> SehirId { get; set; }
        public string UlkeKodu { get; set; }
        public string Tel { get; set; }
        public string VDaire { get; set; }
        public string VNo_Tc { get; set; }
        public string Email { get; set; }
    
        public virtual iller iller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokCikisUst> tblStokCikisUsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokGirisUst> tblStokGirisUsts { get; set; }
    }
}
