//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGiris.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokGirisAlt
    {
        public int Id { get; set; }
        public string GirisKod { get; set; }
        public Nullable<int> GirisSira { get; set; }
        public string Barkod { get; set; }
        public string UrunKod { get; set; }
        public string LotSeriNo { get; set; }
        public string Birim { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
    }
}
