//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGiris.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokCikisUst
    {
        public int Id { get; set; }
        public string CikisKod { get; set; }
        public Nullable<int> CariId { get; set; }
        public string CikisTur { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<int> Iskonto { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<int> SatisMiktar { get; set; }
    
        public virtual tblCari tblCari { get; set; }
    }
}
