//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGiris.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunKayit
    {
        public int Id { get; set; }
        public string UrunKodu { get; set; }
        public string LotSeriNo { get; set; }
        public string Aciklama { get; set; }
        public string Mensei { get; set; }
        public Nullable<int> BirimId { get; set; }
        public string MarkaId { get; set; }
        public Nullable<byte> KdvOran { get; set; }
    
        public virtual tblBirim tblBirim { get; set; }
    }
}
