//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGiris.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStokCikisHepsi
    {
        public string CikisKod { get; set; }
        public Nullable<int> SatisMiktar { get; set; }
        public Nullable<decimal> KdvDahil { get; set; }
        public Nullable<int> KdvOran { get; set; }
        public Nullable<decimal> SatisFiyat { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> Miktar { get; set; }
        public string Birim { get; set; }
        public string LotSeriNo { get; set; }
        public string UrunKod { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> CikisSira { get; set; }
        public int Id { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
        public string CikisTur { get; set; }
        public string FaturaNo { get; set; }
        public string CariAd { get; set; }
        public string CariKod { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<int> Iskonto { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public string VNo_Tc { get; set; }
        public string VDaire { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
    }
}
